<a href="https://colab.research.google.com/github/MohdDilshad-nitk/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
np1 = np.random.rand(3,4)
np1

array([[0.98517733, 0.70491622, 0.71737191, 0.5570986 ],
       [0.02270013, 0.70029124, 0.27943093, 0.47873318],
       [0.03137009, 0.85844593, 0.22260419, 0.66829066]])

In [3]:
np1.dtype #default type

dtype('float64')

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7784,  0.7250, -0.6567,  0.7292],
        [ 1.7394, -3.4354,  0.4141, -0.0733],
        [ 1.1683,  0.4967, -0.5942,  0.3549]])

In [5]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
t3 = torch.tensor(np1)
t3

tensor([[0.9852, 0.7049, 0.7174, 0.5571],
        [0.0227, 0.7003, 0.2794, 0.4787],
        [0.0314, 0.8584, 0.2226, 0.6683]], dtype=torch.float64)