<a href="https://colab.research.google.com/github/MohdDilshad-nitk/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
np1 = np.random.rand(3,4)
np1

array([[0.98517733, 0.70491622, 0.71737191, 0.5570986 ],
       [0.02270013, 0.70029124, 0.27943093, 0.47873318],
       [0.03137009, 0.85844593, 0.22260419, 0.66829066]])

In [3]:
np1.dtype #default type

dtype('float64')

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7784,  0.7250, -0.6567,  0.7292],
        [ 1.7394, -3.4354,  0.4141, -0.0733],
        [ 1.1683,  0.4967, -0.5942,  0.3549]])

In [5]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
t3 = torch.tensor(np1)
t3

tensor([[0.9852, 0.7049, 0.7174, 0.5571],
        [0.0227, 0.7003, 0.2794, 0.4787],
        [0.0314, 0.8584, 0.2226, 0.6683]], dtype=torch.float64)

In [7]:
 t4 = torch.arange(10)
 t4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# reshape and view
t4 = t4.reshape(2,5)
t4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# reshaping without exactly knowing the total elements using -1
t5 = torch.arange(24)
t5 = t5.reshape(2,-1)
t5

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [10]:
# similar is view
t5 = torch.arange(10)
t5 = t5.view(2,5)
t5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# change in og tensor will change the reshaped tensor

t6 = torch.arange(10)
t7 = t6.reshape(5,2)
print(t7)
t6[0] = 100
t7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


tensor([[100,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [16]:
# slicing

t8 = torch.arange(10)
t8 = t8.reshape(5,2)
print(t8)
print(t8[:,1]) # all rows and the first column
print(t8[:,1:]) # all rows and all columns from first onwards

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])


## Tensor Math

In [17]:
tensor_a  = torch.tensor([1,2,3,4])
tensor_b  = torch.tensor([5,6,7,8])

In [18]:
# add
add = tensor_a + tensor_b
add

tensor([ 6,  8, 10, 12])

In [19]:
# addition_long head
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
sub = tensor_a - tensor_b
print(sub)
# subtraction long head
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])


tensor([-4, -4, -4, -4])

In [21]:
# multiply
mul = tensor_a * tensor_b
print(mul)
# multiplication long head
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])


tensor([ 5, 12, 21, 32])

In [22]:
# division
div = tensor_a / tensor_b
print(div)
# division long head
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [23]:
# remainders
rem = tensor_a % tensor_b
print(rem)
# remainder long head
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])


tensor([1, 2, 3, 4])

In [24]:
# exponent
exp = tensor_a ** tensor_b
print(exp)
# exponent long head
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])


tensor([    1,    64,  2187, 65536])

In [25]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [26]:
# reassignment
# tensor_a = tensor_a.add(tensor_b)

# or use the _
tensor_a.add_(tensor_b)


tensor([ 6,  8, 10, 12])